2020-05-15 14:48:39,158 - __main__ - ERROR - This is an error
2020-05-15 14:48:39,164 - __main__ - ERROR - Chaky raised an error
2020-05-15 14:48:39,169 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-70-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-05-15 16:13:46,219 - __main__ - ERROR - This is an error
2020-05-15 16:13:46,221 - __main__ - ERROR - Chaky raised an error
2020-05-15 16:13:46,223 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-44-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-05-15 16:14:30,628 - __main__ - ERROR - This is an error
2020-05-15 16:14:30,630 - __main__ - ERROR - Chaky raised an error
2020-05-15 16:14:30,634 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-44-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-05-17 17:09:29,384 - __main__ - ERROR - This is an error
2020-05-17 17:09:29,386 - __main__ - ERROR - Chaky raised an error
2020-05-17 17:09:29,389 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-44-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-05-18 15:43:07,429 - __main__ - ERROR - This is an error
2020-05-18 15:43:07,434 - __main__ - ERROR - Chaky raised an error
2020-05-18 15:43:07,440 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-44-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-05-18 15:47:34,783 - __main__ - ERROR - This is an error
2020-05-18 15:47:34,787 - __main__ - ERROR - Chaky raised an error
2020-05-18 15:47:34,792 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-46-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-05-24 15:00:22,381 - __main__ - ERROR - This is an error
2020-05-24 15:00:22,383 - __main__ - ERROR - Chaky raised an error
2020-05-24 15:00:22,385 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-05-24 19:39:16,611 - __main__ - ERROR - This is an error
2020-05-24 19:39:16,613 - __main__ - ERROR - Chaky raised an error
2020-05-24 19:39:16,616 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-05-30 07:57:59,534 - __main__ - ERROR - This is an error
2020-05-30 07:57:59,536 - __main__ - ERROR - Chaky raised an error
2020-05-30 07:57:59,538 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-06-03 11:38:38,964 - __main__ - ERROR - This is an error
2020-06-03 11:38:38,966 - __main__ - ERROR - Chaky raised an error
2020-06-03 11:38:38,967 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-06-03 11:39:42,242 - __main__ - ERROR - This is an error
2020-06-03 11:39:42,245 - __main__ - ERROR - Chaky raised an error
2020-06-03 11:39:42,246 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-06-03 11:57:03,310 - __main__ - ERROR - This is an error
2020-06-03 11:57:03,313 - __main__ - ERROR - Chaky raised an error
2020-06-03 11:57:03,315 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-06-03 14:00:13,471 - __main__ - ERROR - This is an error
2020-06-03 14:00:13,473 - __main__ - ERROR - Chaky raised an error
2020-06-03 14:00:13,474 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-06-03 14:00:43,819 - __main__ - ERROR - This is an error
2020-06-03 14:00:43,821 - __main__ - ERROR - Chaky raised an error
2020-06-03 14:00:43,822 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
2020-06-03 14:09:19,044 - __main__ - ERROR - This is an error
2020-06-03 14:09:19,046 - __main__ - ERROR - Chaky raised an error
2020-06-03 14:09:19,047 - __main__ - ERROR - Exception occured
Traceback (most recent call last):
  File "<ipython-input-45-61a38891412c>", line 41, in <module>
    c = a / b
ZeroDivisionError: division by zero
